### ISSUE TITLE
Wrong label used for plugins

### ISSUE THREAD

**Issue by saitho** [Epixskill/recent-content-widget#4]
Plugin elements (CType=list) show up with the wrong label in the widget.

In TypoScript plugins are defined like this:
```
mod.wizards.newContentElement.wizardItems.plugins {
  elements {
    sfregister_create {
      iconIdentifier = sf-register-extension
      title = LLL:EXT:sf_register/Resources/Private/Language/locallang_be.xlf:tt_content.list_type_create
      description = LLL:EXT:sf_register/Resources/Private/Language/locallang_be.xlf:tt_content.list_type_create_description
      tt_content_defValues {
        CType = list
        list_type = sfregister_create
      }
    }
  }
}
```

`RecentContentWidget::getCTypeTranslationString` will therefore use the title of the last plugin, instead of the actually expected title "Insert plugin". Ideally, the actual plugin name used in that content should be displayed.

**Comment by Epixskill** [comment]
This is should be solved in https://github.com/Epixskill/recent-content-widget/releases/tag/v1.1.3

**Comment by saitho** [comment]
Yes, v.1.1.3 shows "Type: General Plugin".
